import type { PagesFunction } from '@cloudflare/workers-types'; import type { Book,Category,Copy,Env,Settings,User } from './_lib/types'; import { currentUser,hashPassword,verifyPassword,cookie,sessionId,requireCsrf,sameOrigin } from './_lib/security'; import { loginBlocked,recordLoginFailure,clearLoginLimit } from './_lib/rate-limit'; import { esc,redirect,today,isColor,isImage,httpsUrl,csvCell,securityHeaders,limitRequestBody } from './_lib/util'; import { publicHome,bookPage,loginPage,adminPage } from './_lib/views';
const settings=async(env:Env)=>env.DB.prepare('SELECT library_name,site_title,primary_color,banner_image_id FROM settings WHERE id=1').first<Settings>();
const html=(body:string,status=200)=>new Response(body,{status,headers:securityHeaders({'content-type':'text/html;charset=UTF-8','cache-control':'no-store'})});
const fail=(message:string,status=400)=>new Response(message,{status,headers:securityHeaders({'content-type':'text/plain;charset=UTF-8','cache-control':'no-store'})});
const parseForm=async(request:Request)=>{try{return await request.formData();}catch{return null;}};
const isIsoDate=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`))&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
async function admin(request:Request,env:Env,user:User,path:string){const s=await settings(env);
if(!s)return fail('Configuração ausente');
 if(path==='/admin/livros.csv'&&request.method==='GET'){const rows=await env.DB.prepare("SELECT b.id,b.title,b.author,c.name category_name,b.isbn,(SELECT count(*) FROM copies x WHERE x.book_id=b.id) total_copies,(SELECT count(*) FROM copies x WHERE x.book_id=b.id AND x.active=1 AND NOT EXISTS(SELECT 1 FROM loans l WHERE l.copy_id=x.id AND l.returned_at IS NULL)) available,b.archived FROM books b JOIN categories c ON c.id=b.category_id ORDER BY b.title").all<any>();
const header=['ID','Título','Autor','Categoria','ISBN','Exemplares totais','Exemplares disponíveis','Situação'];
const lines=rows.results.map(b=>[b.id,b.title,b.author,b.category_name,b.isbn??'',b.total_copies,b.available,b.archived?'Arquivado':'Ativo'].map(csvCell).join(';'));
return new Response('\uFEFF'+[header.map(csvCell).join(';'),...lines].join('\r\n'),{headers:securityHeaders({'content-type':'text/csv;charset=UTF-8','content-disposition':'attachment; filename="catalogo.csv"','cache-control':'no-store'})});}
 if(path==='/admin/acessos'&&request.method==='GET'){const rows=await env.DB.prepare('SELECT e.id,e.username,e.succeeded,e.occurred_at,l.name librarian_name FROM login_events e LEFT JOIN librarians l ON l.id=e.librarian_id ORDER BY e.occurred_at DESC LIMIT 100').all<any>();
return html(adminPage(s,user,`<div class="admin-page-heading"><div><p class="overline">Segurança</p><h1>Histórico de acessos</h1><p class="page-lead">Últimos 100 registros, com retenção automática de 180 dias.</p></div></div><div class="panel table-panel"><div class="table-scroll"><table><thead><tr><th>Data e hora</th><th>Conta</th><th>Resultado</th></tr></thead><tbody>${rows.results.length?rows.results.map(e=>`<tr><td>${esc(e.occurred_at)}</td><td>${esc(e.librarian_name||e.username)}</td><td><span class="access-result ${e.succeeded?'is-success':'is-failure'}">${e.succeeded?'Sucesso':'Falha'}</span></td></tr>`).join(''):'<tr><td colspan="3">Nenhum acesso registrado.</td></tr>'}</tbody></table></div></div>`,'Histórico de acessos'));}
 if(path==='/admin/seguranca/senha'&&request.method==='GET')return html(adminPage(s,user,`<div class="admin-page-heading"><div><p class="overline">Segurança da conta</p><h1>Alterar senha</h1><p class="page-lead">As sessões atuais serão encerradas depois da alteração.</p></div></div><div class="panel form-panel"><form method="post" action="/admin/seguranca/senha"><input type="hidden" name="csrf" value="${user.csrf}"><label for="current-password">Senha atual<input id="current-password" type="password" name="current_password" autocomplete="current-password" required></label><label for="new-password">Nova senha<input id="new-password" type="password" name="new_password" minlength="12" autocomplete="new-password" required><small class="field-help">Use pelo menos 12 caracteres.</small></label><label for="confirm-password">Confirmar nova senha<input id="confirm-password" type="password" name="confirm_password" minlength="12" autocomplete="new-password" required></label><button class="button" type="submit">Alterar senha</button></form></div>`,'Alterar senha'));
 if(path==='/admin/seguranca/senha'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const current=String(f.get('current_password')||''),next=String(f.get('new_password')||''),confirm=String(f.get('confirm_password')||'');
if(next.length<12)return fail('A nova senha deve ter pelo menos 12 caracteres.');
if(next!==confirm)return fail('A confirmação da nova senha não coincide.');
const row=await env.DB.prepare('SELECT password_hash FROM librarians WHERE id=? AND active=1').bind(user.id).first<{password_hash:string}>();
if(!row||!(await verifyPassword(current,row.password_hash)))return fail('A senha atual está incorreta.');
const hashed=await hashPassword(next);
await env.DB.batch([env.DB.prepare('UPDATE librarians SET password_hash=? WHERE id=?').bind(hashed,user.id),env.DB.prepare('DELETE FROM sessions WHERE librarian_id=?').bind(user.id)]);
return redirect('/login?changed=1');}
 if(path==='/admin'){const [a,b,c,d]=await Promise.all([env.DB.prepare('SELECT count(*) n FROM books WHERE archived=0').first<any>(),env.DB.prepare('SELECT count(*) n FROM copies WHERE active=1').first<any>(),env.DB.prepare('SELECT count(*) n FROM loans WHERE returned_at IS NULL').first<any>(),env.DB.prepare("SELECT count(*) n FROM loans WHERE returned_at IS NULL AND due_date < date('now','localtime')").first<any>()]);
return html(adminPage(s,user,`<div class="admin-page-heading"><div><p class="overline">Visão geral</p><h1>Painel administrativo</h1><p class="page-lead">Uma visão rápida do acervo e das tarefas da biblioteca.</p></div><a class="button" href="/admin/livros/novo">Novo livro</a></div><div class="stats admin-stats"><div class="panel stat-card"><span class="stat-label">Acervo ativo</span><div class="stat">${a?.n??0}</div><a href="/admin/livros">Ver livros →</a></div><div class="panel stat-card"><span class="stat-label">Exemplares ativos</span><div class="stat">${b?.n??0}</div><a href="/admin/livros">Gerenciar exemplares →</a></div><div class="panel stat-card"><span class="stat-label">Empréstimos ativos</span><div class="stat">${c?.n??0}</div><a href="/admin/emprestimos?filtro=ativos">Acompanhar empréstimos →</a></div><div class="panel stat-card ${d?.n?'has-alert':''}"><span class="stat-label">Atrasados</span><div class="stat">${d?.n??0}</div><a href="/admin/emprestimos?filtro=atrasados">Ver atrasados →</a></div></div><section class="quick-actions panel"><div><p class="overline">Atalhos</p><h2>Tarefas frequentes</h2></div><div class="quick-action-grid"><a href="/admin/livros/novo">Cadastrar livro <span>↗</span></a><a href="/admin/emprestimos/novo">Registrar empréstimo <span>↗</span></a><a href="/admin/categorias">Organizar categorias <span>↗</span></a><a href="/admin/livros.csv">Exportar catálogo (CSV) <span>↓</span></a></div></section>`, 'Painel'));}
 if(path==='/admin/livros'&&request.method==='GET'){const q=new URL(request.url).searchParams.get('q')?.trim()||'';
const rows=await env.DB.prepare("SELECT b.*,c.name category_name,(SELECT count(*) FROM copies x WHERE x.book_id=b.id) copies,(SELECT count(*) FROM loans l JOIN copies x ON x.id=l.copy_id WHERE x.book_id=b.id AND l.returned_at IS NULL) active_loans FROM books b JOIN categories c ON c.id=b.category_id WHERE (?='' OR b.title LIKE '%'||?||'%' OR b.author LIKE '%'||?||'%' OR coalesce(b.isbn,'') LIKE '%'||?||'%') ORDER BY b.archived,b.title").bind(q,q,q,q).all<any>();
return html(adminPage(s,user,`<div class="admin-page-heading"><div><p class="overline">Acervo</p><h1>Livros</h1></div><div class="heading-actions"><a class="button button-secondary" href="/admin/livros.csv">Exportar catálogo (CSV)</a><a class="button" href="/admin/livros/novo">Novo livro</a></div></div><form class="admin-search" method="get" action="/admin/livros"><label for="admin-book-search">Pesquisar livros<input id="admin-book-search" name="q" value="${esc(q)}" placeholder="Título, autor ou ISBN"><small class="field-help">A pesquisa é feita diretamente no banco.</small></label><button class="button" type="submit">Pesquisar</button>${q?'<a class="button button-secondary" href="/admin/livros">Limpar</a>':''}</form><p class="result-count">${rows.results.length} resultado(s)</p><div class="grid">${rows.results.length?rows.results.map(b=>`<article class="card"><div class="book-card-admin-head"><span class="record-status ${b.archived?'is-archived':'is-active'}">${b.archived?'Arquivado':'Ativo'}</span><span>#${b.id}</span></div><h2>${esc(b.title)}</h2><p>${esc(b.author)} · ${esc(b.category_name)}</p><p>${b.copies} exemplar(es)${b.active_loans?` · ${b.active_loans} emprestado(s)`:''}</p><p class="actions"><a class="button" href="/admin/livros/${b.id}/editar">Editar</a><a class="button button-secondary" href="/admin/livros/${b.id}/exemplares">Exemplares</a>${!b.archived?`<form method="post" action="/admin/livros/${b.id}/arquivar"><input type="hidden" name="csrf" value="${user.csrf}"><button class="button-warning">Arquivar</button></form>`:''}<form method="post" action="/admin/livros/${b.id}/excluir" data-confirm="${b.active_loans?'Este livro tem empréstimos ativos. A exclusão permanente removerá o livro, seus exemplares e todo o histórico, inclusive empréstimos não devolvidos. Confirme a operação.':'Excluir este livro permanentemente? Seus exemplares e todo o histórico de empréstimos serão removidos.'}"><input type="hidden" name="csrf" value="${user.csrf}">${b.active_loans?'<label><input type="checkbox" name="confirmation" required> Confirmo apagar também empréstimos ativos</label>':''}<button class="danger">Excluir definitivamente</button></form></p></article>`).join(''):'<div class="empty-state"><h3>Nenhum livro encontrado</h3><p>Tente outro título, autor ou ISBN.</p></div>'}</div>`,'Livros'));}
 if(path==='/admin/livros/novo'&&request.method==='GET'){const cats=await env.DB.prepare('SELECT * FROM categories ORDER BY name').all<any>();
return html(adminPage(s,user,bookForm(cats.results,null,user.csrf),'Novo livro'));}
 const edit=path.match(/^\/admin\/livros\/(\d+)\/editar$/);
if(edit&&request.method==='GET'){const b=await env.DB.prepare('SELECT * FROM books WHERE id=?').bind(edit[1]).first<any>();
const cats=await env.DB.prepare('SELECT * FROM categories ORDER BY name').all<any>();
return html(adminPage(s,user,bookForm(cats.results,b,user.csrf),'Editar livro'));}
 if(path==='/admin/livros'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const legacyCover=f.get('cover');
if(legacyCover instanceof File&&legacyCover.size)return fail('Capas devem ser cadastradas por uma URL HTTPS.');
const id=Number(f.get('id')||0),title=String(f.get('title')||'').trim(),author=String(f.get('author')||'').trim(),category=Number(f.get('category_id')),coverUrl=httpsUrl(String(f.get('cover_url')||''));
if(!title||!author||!category)return fail('Preencha título, autor e categoria.');
if(String(f.get('cover_url')||'').trim()&&!coverUrl)return fail('A URL da capa deve ser HTTPS, válida e ter no máximo 2048 caracteres.');
if(id){await env.DB.prepare('UPDATE books SET title=?,author=?,isbn=?,description=?,category_id=?,cover_url=? WHERE id=?').bind(title,author,String(f.get('isbn')||'')||null,String(f.get('description')||'')||null,category,coverUrl,id).run();
return redirect('/admin/livros');}const created=await env.DB.prepare('INSERT INTO books(title,author,isbn,description,category_id,cover_url) VALUES(?,?,?,?,?,?)').bind(title,author,String(f.get('isbn')||'')||null,String(f.get('description')||'')||null,category,coverUrl).run();
return redirect(`/admin/livros/${created.meta.last_row_id}/exemplares`);}
 const copyPage=path.match(/^\/admin\/livros\/(\d+)\/exemplares$/);
if(copyPage&&request.method==='GET'){const rows=await env.DB.prepare("SELECT c.*,EXISTS(SELECT 1 FROM loans l WHERE l.copy_id=c.id AND l.returned_at IS NULL) borrowed FROM copies c WHERE c.book_id=? ORDER BY c.code").bind(copyPage[1]).all<any>();
return html(adminPage(s,user,`<h1>Exemplares</h1><form method="post" action="/admin/livros/${copyPage[1]}/exemplares"><input type="hidden" name="csrf" value="${user.csrf}"><input name="code" placeholder="Código do exemplar" required><button>Adicionar</button></form><ul>${rows.results.map(c=>`<li>${esc(c.code)} — ${c.active?'Ativo':'Inativo'} ${c.borrowed?'(emprestado)':`<form style="display:inline" method="post" action="/admin/exemplares/${c.id}/alternar"><input type="hidden" name="csrf" value="${user.csrf}"><button>${c.active?'Desativar':'Reativar'}</button></form>`}</li>`).join('')}</ul>`,'Exemplares'));}
 if(copyPage&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');try{await env.DB.prepare('INSERT INTO copies(book_id,code) VALUES(?,?)').bind(copyPage[1],String(f.get('code')||'').trim()).run();}catch{return fail('Código de exemplar já existe.');}return redirect(`/admin/livros/${copyPage[1]}/exemplares`);}
 const toggleCopy=path.match(/^\/admin\/exemplares\/(\d+)\/alternar$/);
if(toggleCopy&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const borrowed=await env.DB.prepare('SELECT 1 FROM loans WHERE copy_id=? AND returned_at IS NULL').bind(toggleCopy[1]).first();
if(borrowed)return fail('Não é possível desativar exemplar emprestado.');
await env.DB.prepare('UPDATE copies SET active=1-active WHERE id=?').bind(toggleCopy[1]).run();
return redirect('/admin/livros');}
 const deleteBook=path.match(/^\/admin\/livros\/(\d+)\/excluir$/);
if(deleteBook&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const id=Number(deleteBook[1]);
const active=await env.DB.prepare('SELECT count(*) n FROM loans l JOIN copies c ON c.id=l.copy_id WHERE c.book_id=? AND l.returned_at IS NULL').bind(id).first<{n:number}>();
if((active?.n??0)>0&&f.get('confirmation')!=='on')return fail('Confirme a exclusão reforçada para apagar também os empréstimos ativos.');
const book=await env.DB.prepare('SELECT cover_image_id FROM books WHERE id=?').bind(id).first<{cover_image_id:number|null}>();
const imageId=book?.cover_image_id??null;
const statements=[env.DB.prepare('DELETE FROM loans WHERE copy_id IN (SELECT id FROM copies WHERE book_id=?)').bind(id),env.DB.prepare('DELETE FROM copies WHERE book_id=?').bind(id),env.DB.prepare('DELETE FROM books WHERE id=?').bind(id)];
if(imageId)statements.push(env.DB.prepare('DELETE FROM images WHERE id=? AND NOT EXISTS(SELECT 1 FROM books WHERE cover_image_id=?) AND NOT EXISTS(SELECT 1 FROM settings WHERE banner_image_id=?)').bind(imageId,imageId,imageId));
await env.DB.batch(statements);
return redirect('/admin/livros');}
 const archive=path.match(/^\/admin\/livros\/(\d+)\/arquivar$/);
if(archive&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
await env.DB.prepare('UPDATE books SET archived=1 WHERE id=?').bind(archive[1]).run();
return redirect('/admin/livros');}
 if(path==='/admin/categorias'&&request.method==='GET'){const rows=await env.DB.prepare('SELECT c.*,count(b.id) book_count FROM categories c LEFT JOIN books b ON b.category_id=c.id GROUP BY c.id ORDER BY c.name').all<any>();
return html(adminPage(s,user,`<h1>Categorias</h1><form method="post" action="/admin/categorias"><input type="hidden" name="csrf" value="${user.csrf}"><input name="name" placeholder="Nome" required><input name="description" placeholder="Descrição"><button>Adicionar</button></form><ul>${rows.results.map(c=>`<li>${esc(c.name)} (${c.book_count}) ${c.book_count===0?`<form style="display:inline" method="post" action="/admin/categorias/${c.id}/excluir"><input type="hidden" name="csrf" value="${user.csrf}"><button class="danger">Excluir</button></form>`:''}</li>`).join('')}</ul>`,'Categorias'));}
 const catDelete=path.match(/^\/admin\/categorias\/(\d+)\/excluir$/);
if(catDelete&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const x=await env.DB.prepare('SELECT count(*) n FROM books WHERE category_id=?').bind(catDelete[1]).first<any>();
if(x?.n)return fail('Não é possível excluir categoria com livros vinculados.');
await env.DB.prepare('DELETE FROM categories WHERE id=?').bind(catDelete[1]).run();
return redirect('/admin/categorias');}
 if(path==='/admin/categorias'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
await env.DB.prepare('INSERT INTO categories(name,description) VALUES(?,?)').bind(String(f.get('name')||'').trim(),String(f.get('description')||'').trim()).run();
return redirect('/admin/categorias');}
 if(path==='/admin/emprestimos'&&request.method==='GET'){const filter=new URL(request.url).searchParams.get('filtro')||'todos';
const where=filter==='ativos'?'AND l.returned_at IS NULL':filter==='atrasados'?"AND l.returned_at IS NULL AND l.due_date < date('now','localtime')":filter==='devolvidos'?'AND l.returned_at IS NOT NULL':'';
const [rows,historyBooks]=await Promise.all([env.DB.prepare(`SELECT l.*,c.code,b.title FROM loans l JOIN copies c ON c.id=l.copy_id JOIN books b ON b.id=c.book_id WHERE 1=1 ${where} ORDER BY l.loan_date DESC`).all<any>(),env.DB.prepare('SELECT b.id,b.title,count(l.id) history_count FROM books b JOIN copies c ON c.book_id=b.id JOIN loans l ON l.copy_id=c.id AND l.returned_at IS NOT NULL GROUP BY b.id,b.title ORDER BY b.title').all<any>()]);
return html(adminPage(s,user,`<div class="actions"><h1>Empréstimos</h1><a class="button" href="/admin/emprestimos/novo">Novo empréstimo</a></div><p class="actions"><a href="?filtro=todos">Todos</a> <a href="?filtro=ativos">Ativos</a> <a href="?filtro=atrasados">Atrasados</a> <a href="?filtro=devolvidos">Devolvidos</a></p>${historyBooks.results.length?`<section class="panel"><h2>Histórico por livro</h2><ul>${historyBooks.results.map(b=>`<li><strong>${esc(b.title)}</strong> · ${b.history_count} encerrado(s) <form style="display:inline" method="post" action="/admin/livros/${b.id}/historico/excluir" data-confirm="Excluir permanentemente todo o histórico encerrado deste livro?"><input type="hidden" name="csrf" value="${user.csrf}"><button class="danger">Limpar histórico</button></form></li>`).join('')}</ul></section>`:''}<div style="overflow:auto"><table><tr><th>Livro</th><th>Exemplar</th><th>Responsável</th><th>Retirada</th><th>Prazo</th><th>Situação</th><th></th></tr>${rows.results.map(l=>`<tr><td>${esc(l.title)}</td><td>${esc(l.code)}</td><td>${esc(l.borrower_name)}</td><td>${l.loan_date}</td><td>${l.due_date}</td><td>${l.returned_at?'Devolvido':l.due_date<today()?'<span class="unavailable">Atrasado</span>':'Ativo'}</td><td>${!l.returned_at?`<form method="post" action="/admin/emprestimos/${l.id}/devolver"><input type="hidden" name="csrf" value="${user.csrf}"><button>Devolver</button></form>`:`<form method="post" action="/admin/emprestimos/${l.id}/excluir" data-confirm="Excluir permanentemente este registro de empréstimo?"><input type="hidden" name="csrf" value="${user.csrf}"><button class="danger">Excluir registro</button></form>`}</td></tr>`).join('')}</table></div>`,'Empréstimos'));}
 if(path==='/admin/emprestimos/novo'&&request.method==='GET'){const rows=await env.DB.prepare("SELECT c.*,b.title,b.author FROM copies c JOIN books b ON b.id=c.book_id WHERE c.active=1 AND b.archived=0 AND NOT EXISTS(SELECT 1 FROM loans l WHERE l.copy_id=c.id AND l.returned_at IS NULL) ORDER BY b.title,c.code").all<any>();
return html(adminPage(s,user,loanForm(rows.results,user.csrf),'Novo empréstimo'));}
 if(path==='/admin/emprestimos'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const copy=Number(f.get('copy_id')),loan=String(f.get('loan_date')||today()),due=String(f.get('due_date')||'');
if(!due||!String(f.get('borrower_name')||'').trim())return fail('Preencha os dados.');
if(!isIsoDate(loan)||!isIsoDate(due))return fail('Informe datas válidas.');
if(due<loan)return fail('A data de devolução não pode ser anterior à data do empréstimo.');
try{await env.DB.prepare('INSERT INTO loans(copy_id,borrower_name,loan_date,due_date) VALUES(?,?,?,?)').bind(copy,String(f.get('borrower_name')).trim(),loan,due).run();}catch{return fail('Este exemplar não está disponível para empréstimo.');}return redirect('/admin/emprestimos');}
 const clearHistory=path.match(/^\/admin\/livros\/(\d+)\/historico\/excluir$/);
if(clearHistory&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
await env.DB.prepare('DELETE FROM loans WHERE returned_at IS NOT NULL AND copy_id IN (SELECT id FROM copies WHERE book_id=?)').bind(clearHistory[1]).run();
return redirect('/admin/emprestimos?filtro=devolvidos');}
 const deleteLoan=path.match(/^\/admin\/emprestimos\/(\d+)\/excluir$/);
if(deleteLoan&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const result=await env.DB.prepare('DELETE FROM loans WHERE id=? AND returned_at IS NOT NULL').bind(deleteLoan[1]).run();
if(!result.meta.changes)return fail('Somente empréstimos já devolvidos podem ser excluídos.');
return redirect('/admin/emprestimos?filtro=devolvidos');}
 const ret=path.match(/^\/admin\/emprestimos\/(\d+)\/devolver$/);
if(ret&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
await env.DB.prepare("UPDATE loans SET returned_at=? WHERE id=? AND returned_at IS NULL").bind(today(),ret[1]).run();
return redirect('/admin/emprestimos');}
 if(path==='/admin/configuracao'&&request.method==='GET')return html(adminPage(s,user,settingsForm(s,user.csrf),'Configuração'));
 if(path==='/admin/configuracao'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!requireCsrf(request,user,f))return fail('CSRF inválido');
const color=String(f.get('primary_color')||'');
if(!isColor(color))return fail('Cor inválida.');
const removeBanner=f.get('remove_banner')==='on';
const file=f.get('banner');
if(file instanceof File&&file.size&&!(await isImage(file,600*1024)))return fail('Banner inválido ou maior que 600 KB.');
const old=await env.DB.prepare('SELECT banner_image_id FROM settings WHERE id=1').first<{banner_image_id:number|null}>();let banner:number|null=old?.banner_image_id??null;let createdBannerId:number|null=null;try{if(file instanceof File&&file.size){const result=await env.DB.prepare('INSERT INTO images(mime_type,content,size) VALUES(?,?,?)').bind(file.type,await new Response(file).arrayBuffer(),file.size).run();banner=Number(result.meta.last_row_id);createdBannerId=banner;}else if(removeBanner)banner=null;
const statements=[env.DB.prepare('UPDATE settings SET library_name=?,site_title=?,primary_color=?,banner_image_id=? WHERE id=1').bind(String(f.get('library_name')||'').trim(),String(f.get('site_title')||'').trim(),color,banner)];
if(old?.banner_image_id&&old.banner_image_id!==banner)statements.push(env.DB.prepare('DELETE FROM images WHERE id=? AND NOT EXISTS(SELECT 1 FROM books WHERE cover_image_id=?) AND NOT EXISTS(SELECT 1 FROM settings WHERE banner_image_id=?)').bind(old.banner_image_id,old.banner_image_id,old.banner_image_id));
await env.DB.batch(statements);}catch(error){if(createdBannerId!==null)await env.DB.prepare('DELETE FROM images WHERE id=? AND NOT EXISTS(SELECT 1 FROM books WHERE cover_image_id=?) AND NOT EXISTS(SELECT 1 FROM settings WHERE banner_image_id=?)').bind(createdBannerId,createdBannerId,createdBannerId).run();throw error;}return redirect('/admin/configuracao');}
 return fail('Rota administrativa não encontrada.'); }
function bookForm(cats:any[],b:any,csrf:string){const coverUrl=String(b?.cover_url||'');
return `<h1>${b?'Editar':'Novo'} livro</h1><form method="post" action="/admin/livros"><input type="hidden" name="csrf" value="${csrf}">${b?`<input type="hidden" name="id" value="${b.id}">`:''}<input name="title" value="${esc(b?.title)}" placeholder="Título" required><input name="author" value="${esc(b?.author)}" placeholder="Autor" required><input name="isbn" value="${esc(b?.isbn)}" placeholder="ISBN"><textarea name="description" placeholder="Descrição">${esc(b?.description)}</textarea><select name="category_id" required><option value="">Categoria</option>${cats.map(c=>`<option value="${c.id}" ${b?.category_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')} </select><label for="cover-url">URL da capa<input id="cover-url" type="url" name="cover_url" value="${esc(coverUrl)}" placeholder="https://exemplo.com/capa.jpg" maxlength="2048" inputmode="url" data-cover-url><small class="field-help">Opcional. Use o endereço HTTPS direto da imagem; o arquivo não é armazenado nesta biblioteca.</small></label><div class="cover-preview" aria-live="polite"><img data-cover-preview src="${esc(coverUrl)}" alt="Pré-visualização da capa de ${esc(b?.title||'livro')}" width="160" height="230" referrerpolicy="no-referrer"${coverUrl?'':' hidden'}><span data-cover-preview-empty${coverUrl?' hidden':''}>A pré-visualização aparecerá aqui.</span></div><button>Salvar</button>${b?`<a class="button button-secondary" href="/admin/livros/${b.id}/exemplares">Gerenciar exemplares</a>`:''}</form>`;}
function loanForm(copies:any[],csrf:string){const options=copies.map(c=>`<option value="${c.id}">${esc(c.title)} — ${esc(c.author)} — ${esc(c.code)}</option>`).join('');
const empty=copies.length===0;
return `<h1>Novo empréstimo</h1>${empty?'<p class="form-error" role="alert">Não há exemplares disponíveis para empréstimo. Cadastre um exemplar ou aguarde a devolução de um livro.</p>':''}<form method="post" action="/admin/emprestimos"><input type="hidden" name="csrf" value="${csrf}"><label for="loan-copy">Livro e exemplar<select id="loan-copy" name="copy_id" required ${empty?'disabled':''}><option value="">Selecione um livro e exemplar</option>${options}</select></label><input name="borrower_name" placeholder="Nome do responsável" required ${empty?'disabled':''}><label>Retirada<input type="date" name="loan_date" value="${today()}" required ${empty?'disabled':''}></label><label>Devolução prevista<input type="date" name="due_date" value="${new Date(Date.now()+30*86400000).toISOString().slice(0,10)}" required ${empty?'disabled':''}></label><button ${empty?'disabled':''}>Registrar</button></form>`;}
function settingsForm(s:Settings,csrf:string){return `<h1>Configuração</h1><form method="post" action="/admin/configuracao" enctype="multipart/form-data"><input type="hidden" name="csrf" value="${csrf}"><input name="library_name" value="${esc(s.library_name)}" required><input name="site_title" value="${esc(s.site_title)}" required><label>Cor principal<input type="color" name="primary_color" value="${esc(s.primary_color)}"></label><label>Banner da página inicial<input type="file" name="banner" accept="image/jpeg,image/png,image/webp"><small class="field-help">JPEG, PNG ou WebP de até 600 KB. A imagem aparece no painel à direita da apresentação.</small></label>${s.banner_image_id?'<label class="check-row"><input type="checkbox" name="remove_banner"> Remover banner atual</label>':''}<button>Salvar alterações</button></form>`;}
export const onRequest:PagesFunction<Env>=async({request:incomingRequest,env})=>{try{let request:Request=incomingRequest;const path=new URL(request.url).pathname;const bodyLimit=path==='/login'?16*1024:path==='/admin/configuracao'?700*1024:path.startsWith('/admin')?64*1024:700*1024;const limitedRequest=await limitRequestBody(request,bodyLimit);if(!limitedRequest)return fail('Payload muito grande ou malformado.',413);request=limitedRequest;
if(path.startsWith('/imagens/')){const row=await env.DB.prepare('SELECT mime_type,content FROM images WHERE id=?').bind(path.split('/').pop()).first<{mime_type:string;content:ArrayBuffer|number[]}>();
if(!row)return new Response('Not found',{status:404,headers:securityHeaders({'cache-control':'no-store'})});
const bytes=row.content instanceof ArrayBuffer?new Uint8Array(row.content):new Uint8Array(row.content);
return new Response(bytes,{headers:securityHeaders({'content-type':row.mime_type,'cache-control':'public,max-age=31536000,immutable'})});}if(path==='/login'&&request.method==='GET'){const s=await settings(env),url=new URL(request.url);
return html(loginPage(s!,url.searchParams.has('error'),url.searchParams.has('changed')));}if(path==='/login'&&request.method==='POST'){const f=await parseForm(request);if(!f)return fail('Dados inválidos.');const u=String(f.get('username')||'').trim().slice(0,256),p=String(f.get('password')||'');if(await loginBlocked(env,u))return redirect('/login?error=1');
const row=await env.DB.prepare('SELECT * FROM librarians WHERE username=? AND active=1').bind(u).first<{id:number;password_hash:string}>();
if(!row||!(await verifyPassword(p,row.password_hash))){await recordLoginFailure(env,u);await env.DB.batch([env.DB.prepare('INSERT INTO login_events(username,succeeded) VALUES(?,0)').bind(u),env.DB.prepare("DELETE FROM login_events WHERE occurred_at < datetime('now','-180 days')")]);
return redirect('/login?error=1');}await env.DB.batch([env.DB.prepare('INSERT INTO login_events(librarian_id,username,succeeded) VALUES(?,?,1)').bind(row.id,u),env.DB.prepare("DELETE FROM login_events WHERE occurred_at < datetime('now','-180 days')")]);
const id=sessionId(),csrf=sessionId();
await env.DB.prepare('INSERT INTO sessions(id,librarian_id,csrf_token,expires_at) VALUES(?,?,?,?)').bind(id,row.id,csrf,Date.now()+8*60*60*1000).run();
await clearLoginLimit(env,u);return redirect('/admin',{ 'Set-Cookie':cookie('session',id,8*60*60,new URL(request.url).protocol==='https:')});}if(path==='/logout'&&request.method==='POST'){const raw=request.headers.get('Cookie')?.match(/(?:^|;\s*)session=([^;]+)/)?.[1];const session=raw?await env.DB.prepare('SELECT csrf_token FROM sessions WHERE id=? AND expires_at>?').bind(raw,Date.now()).first<{csrf_token:string}>():null;const f=await parseForm(request);if(!f)return fail('Dados inválidos.');
if(!session||!sameOrigin(request)||f.get('csrf')!==session.csrf_token)return fail('CSRF inválido.');if(raw)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(raw).run();
return redirect('/',{'Set-Cookie':cookie('session','',0,new URL(request.url).protocol==='https:')});}const s=await settings(env);
if(path==='/'&&request.method==='GET'){const url=new URL(request.url),q=url.searchParams.get('q')||'',cat=url.searchParams.get('categoria')||'';
const [cats,books]=await Promise.all([env.DB.prepare('SELECT * FROM categories ORDER BY name').all<Category>(),env.DB.prepare("SELECT b.*,c.name category_name,(SELECT count(*) FROM copies x WHERE x.book_id=b.id AND x.active=1 AND NOT EXISTS(SELECT 1 FROM loans l WHERE l.copy_id=x.id AND l.returned_at IS NULL)) available FROM books b JOIN categories c ON c.id=b.category_id WHERE b.archived=0 AND (?='' OR b.title LIKE '%'||?||'%' OR b.author LIKE '%'||?||'%') AND (?='' OR b.category_id=?) ORDER BY b.title LIMIT 100").bind(q,q,q,cat,cat).all<Book>()]);
return html(publicHome(s!,cats.results,books.results,q,cat));}const bp=path.match(/^\/livros\/(\d+)$/);
if(bp&&request.method==='GET'){const b=await env.DB.prepare('SELECT b.*,c.name category_name FROM books b JOIN categories c ON c.id=b.category_id WHERE b.id=? AND b.archived=0').bind(bp[1]).first<any>();
if(!b)return new Response('Not found',{status:404});
const copies=await env.DB.prepare('SELECT c.*,l.id loan_id FROM copies c LEFT JOIN loans l ON l.copy_id=c.id AND l.returned_at IS NULL WHERE c.book_id=?').bind(bp[1]).all<Copy>();
return html(bookPage(s!,b,copies.results));}const user=await currentUser(request,env);
if(path.startsWith('/admin'))return user?admin(request,env,user,path):redirect('/login');
return new Response('Not found',{status:404,headers:securityHeaders({'cache-control':'no-store'})});}catch(e){console.error('Request failed',e instanceof Error?e.name:'UnknownError');
return new Response('Erro interno.',{status:500,headers:securityHeaders({'content-type':'text/plain;charset=UTF-8','cache-control':'no-store'})});}};
